// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsjL3e3Ab7GXbYozfD2TQ3XyzOnj0z_1k',
    appId: '1:1059852174167:web:fcbebe216bc3d7b45db412',
    messagingSenderId: '1059852174167',
    projectId: 'app-avaliacao2-alexcolman',
    authDomain: 'app-avaliacao2-alexcolman.firebaseapp.com',
    storageBucket: 'app-avaliacao2-alexcolman.appspot.com',
    measurementId: 'G-3JSGMDFYCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD06cJCYa6mzfZAGMQqwws5KQ-6fYfvu9E',
    appId: '1:1059852174167:android:2df76353f19852205db412',
    messagingSenderId: '1059852174167',
    projectId: 'app-avaliacao2-alexcolman',
    storageBucket: 'app-avaliacao2-alexcolman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_zZ6FZzhORcdkZVNXANlj_0_wramj6g',
    appId: '1:1059852174167:ios:11dda064933b15955db412',
    messagingSenderId: '1059852174167',
    projectId: 'app-avaliacao2-alexcolman',
    storageBucket: 'app-avaliacao2-alexcolman.appspot.com',
    iosBundleId: 'com.example.fatecRpNoitePdm2024AppAvaliacao2AlexcolmanIgor',
  );
}
